Support N>1 spanners
posit-dev/great-tables pull request #345
Opened 2024-05-14 23:50 UTC by timkpaine

# Summary
Support more than 1 level of spanners:

```python
from great_tables import GT, exibble
(
    GT(exibble)
    .tab_spanner("A", ["num", "char", "fctr"])
    .tab_spanner("B", ["fctr"])
    .tab_spanner("C", ["num", "char"])
    .tab_spanner("D", ["fctr", "date", "time"])
    .tab_spanner("E", spanners=["B", "C"])
)
```
<img width="1087" alt="Screenshot 2024-05-14 at 19 48 32" src="https://github.com/posit-dev/great-tables/assets/3105306/68dcc45b-5714-4502-88cf-69eb13d606d4">

NOTE:
- I made a design tweak with the underscore under upper level spanners
- Needs tests

# Related GitHub Issues and PRs

- Ref: #221

# Checklist

- [x] I understand and agree to the [Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/).
- [x] I have followed the [Style Guide for Python Code](https://peps.python.org/pep-0008/) as best as possible for the submitted code.
- [x] I have added **pytest** unit tests for any new functionality.

2024-05-14 23:56 UTC, machow commented
Thanks so much--this is really great! Did you want to work on the changes in note? We are more than happy to pick up and work on testing, if you're focused on Loc stuff. This is super helpful--happy to do whatever is most useful!

2024-05-15 00:23 UTC, timkpaine commented
@machow I'm happy to write tests/docs, just need some guidance. The two examples here might be sufficient to assert that their table header structure is created correctly?

```python
from great_tables import GT, exibble

# With stub head
(
    GT(exibble, rowname_col="row", groupname_col="group")
    .tab_spanner("A", ["num", "char", "fctr"])
    .tab_spanner("B", ["fctr"])
    .tab_spanner("C", ["num", "char"])
    .tab_spanner("D", ["fctr", "date", "time"])
    .tab_spanner("E", spanners=["B", "C"])
    # for testing
    .tab_stubhead(label="Group")
)

# Without stub head
(
    GT(exibble)
    .tab_spanner("A", ["num", "char", "fctr"])
    .tab_spanner("B", ["fctr"])
    .tab_spanner("C", ["num", "char"])
    .tab_spanner("D", ["fctr", "date", "time"])
    .tab_spanner("E", spanners=["B", "C"])
)
```

2024-05-15 15:53 UTC, rich-iannone commented
I did some testing and I only found one issues with this (aside from the preexisting issue https://github.com/posit-dev/great-tables/issues/273, which could be fixed later). Here's what I used for one of the more comprehensive tests:

```py
(
  GT(exibble_pl, rowname_col="row", groupname_col="group")
  .fmt_number(columns="num")
  .sub_missing("num")
  .cols_label(num = "Number")
  .tab_spanner(label="1st three", columns = ["num", "char", "fctr"], id="one")
  .tab_spanner(label="2nd three", columns = ["date", "time", "datetime"], id="two")
  .tab_spanner(label="Over both", columns = ["num", "char", "fctr"], id="overbothspanners", spanners="two")
  .tab_spanner(label="3rd level", columns=["char", "num"], id="level3")
  .tab_spanner(label="4th level", columns=["char", "num"], id="level4", )
  .tab_spanner(label="Over two and currency", columns="currency", spanners="two", id="mixed", )
  .tab_spanner(label="Right above currency", columns="currency", level=0, id="over_curr",)
  .tab_spanner(label="Two above currency", columns="currency", level=1)
  .tab_spanner(label="REPLACEMENT", columns="currency", level=1, replace=True)
)
```
<img width="865" alt="spanners_tbl" src="https://github.com/posit-dev/great-tables/assets/5612024/358e20dd-a548-40af-9d3f-90032ed4096e">

This is phenomenal work because everything works as expected. The only thing that doesn't is when `replace=False` is used in the final `.tab_spanner()` call, which should result in an error. I see in the implementation that this arg is not being used and I think we could definitely punt on that one since it crosses into advanced usage.

2024-05-15 15:57 UTC, rich-iannone requested changes
Everything looks great except for the unused `replace=` arg. If you want to leave that til later, I'd suggest removing the arg and associated documentation for this PR.

2024-05-15 16:14 UTC, rich-iannone commented
Also, the following example fails:

```py
from great_tables import GT, md, html
from great_tables.data import gtcars

gtcars_mini = gtcars[["mfr", "model", "year", "hp", "trq", "msrp"]].tail(10)

(
    GT(gtcars_mini, rowname_col="model", groupname_col="mfr")
    .tab_spanner(label=md("*Performance*"), columns=["hp", "trq"])
    .tab_header(
        title=html("Data listing from <strong>gtcars</strong>"),
        subtitle=html("A <span style='font-size:12px;'>small selection</span> of great cars."),
    )
    .cols_label(year="Year Produced", hp="HP", trq="Torque", msrp="Price (USD)")
    .fmt_integer(columns=["year", "hp", "trq"], use_seps=False)
    .fmt_currency(columns="msrp")
    .tab_source_note(source_note="Source: the gtcars dataset within the Great Tables package.")
)
```

I traced it to the validation check:

```py
if id in crnt_spanner_ids:
        raise ValueError(f"Spanner id {id} already exists.")
```

Which is good, but if the `id` is produced from a label *and* the label is created with `md()` we get a `Text` object. I think we need to handle the creation of `id` values from `Text`. Maybe like this?

```py
if id is None:
  if hasattr(label, "text"): # <- We could most probably have a better conditional stmt here
    id = label.text
  else:
    id = label
```

Then the example runs (but we still get bitten by https://github.com/posit-dev/great-tables/issues/273) and produces a GT table.

2024-05-15 16:35 UTC, rich-iannone commented on great_tables/_utils_render_html.py
>              spanners=data._spanners, boxhead=boxhead, include_hidden=False, ids=True
With that change, I get this table from the code presented above:

<img width="917" alt="spanners-id-label-fix" src="https://github.com/posit-dev/great-tables/assets/5612024/aae673ee-126c-49d1-acc7-c14e3a5a22cd">

2024-05-15 19:46 UTC, rich-iannone approved these changes
LGTM!

2024-05-15 20:27 UTC, merged