feat: add `fmt_icon()` method
posit-dev/great-tables pull request #515
Opened 2024-11-20 19:56 UTC by rich-iannone

This PR adds the `fmt_icon()` method. It depends on Font Awesome icons available in the `faicons` library, so that is a new dependency. Whenever that package is updated, new icons from the FA free set will be available. Here's an example of the `fmt_icon()` method in use:

```python
import pandas as pd
from great_tables import GT
animals_foods_df = pd.DataFrame(
    {
        "animals": ["hippo", "fish,spider", "mosquito,locust,frog", "dog,cat", "kiwi-bird"],
        "foods": ["bowl-rice", "egg,pizza-slice", "burger,lemon,cheese", "carrot,hotdog", "bacon"],
    }
)
(
    GT(animals_foods_df)
    .fmt_icon(
        columns=["animals", "foods"],
        height="4em"
    )
    .cols_align(
        align="center",
        columns=["animals", "foods"]
    )
)
```

<img width="554" alt="image" src="https://github.com/user-attachments/assets/dce28186-6bbb-4d40-b39b-498a84531366">

2024-11-25 21:47 UTC, machow commented on great_tables/_formats.py
> +            stroke_width = self.stroke_width
Please test this

2024-11-25 21:48 UTC, machow commented on great_tables/_formats.py
> +                    fill_color = None
Please test this

2024-11-25 21:55 UTC, machow requested changes
This LGTM, if we can polars data wrangling in the second example

2024-11-25 21:55 UTC, machow commented on great_tables/_formats.py
> +    )
Is it possible to just select a few rows of this data. E.g. `towny[[0, 3, 5], :]`. Say maybe the top 2 in each of your groups. It seems easier to get into an example with less setup (a doesn't seem critical to have a comprehensive table).

2024-11-26 17:58 UTC, rich-iannone commented on great_tables/_formats.py
> +            stroke_width = self.stroke_width
Now tested.

2024-11-26 17:58 UTC, rich-iannone commented on great_tables/_formats.py
> +                    fill_color = None
Tests now present for this.

2024-12-10 14:38 UTC, machow approved these changes
LGTM, thanks!

2024-12-10 14:38 UTC, merged